name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          {%- if cookiecutter.package_manager == 'pip' %}
          python -m pip install -r requirements.txt
          {%- elif cookiecutter.package_manager == 'poetry' %}
          python -m pip install poetry
          poetry install
          {%- endif %}
      - name: Test with pytest
        run: |
          {% if cookiecutter.package_manager == 'poetry' %}poetry run {% endif %}pytest
